POST http://localhost:3001/tasks/create
Content-Type: application/json

{
  "title": "Test title",
  "description": "Test Description",
  "status": "todo",
  "priority": "normal",
  "dueDate": "2026-04-25T15:19:00Z"
}
